export const catalogData = [
  {
    "id": `${1}-catalogDataItem`,
    "name": "Brown Givenchy Bag",
    "brand": "Givenchy",
    "price": 2799,
    "rating": 4.3,
    "color": "Brown",
    "style": "Work",
    "material": "Leather",
    "available": "Yes",
    "model": "Givenchy123V_Bag",
    "image": "/media/catalogMedia/BrownGivenchyBag.png",
  },
  {
    "id": `${2}-catalogDataItem`,
    "name": "Orange ZARA Bag",
    "brand": "Zara",
    "price": 1799,
    "rating": 3.8,
    "color": "Orange",
    "style": "Work",
    "material": "Leather",
    "available": "Yes",
    "model": "Zara1098D_Bag",
    "image": "/media/catalogMedia/OrangeZaraBag.png",
  },
  {
    "id": `${3}-catalogDataItem`,
    "name": "Brown Parfois Bag",
    "brand": "Parfois",
    "price": 1799,
    "rating": 4.6,
    "color": "Brown",
    "style": "Evening",
    "material": "Leather",
    "available": "Yes",
    "model": "Parfois654P_Bag",
    "image": "/media/catalogMedia/BrownParfoisBag1.png",
  },
  {
    "id": `${4}-catalogDataItem`,
    "name": "Green Givenchy Bag",
    "brand": "Givenchy",
    "price": 1899,
    "rating": 4.9,
    "color": "Green",
    "style": "Evening",
    "material": "Polyurethane",
    "available": "Yes",
    "model": "Givenchy32OV_Bag",
    "image": "/media/catalogMedia/GreenGivenchyBag.png",
  },
  {
    "id": `${5}-catalogDataItem`,
    "name": "Brown Parfois Bag",
    "brand": "Parfois",
    "price": 1999,
    "rating": 5.0,
    "color": "Brown",
    "style": "School",
    "material": "Textile",
    "available": "Yes",
    "model": "Parfois008Gt_Bag",
    "image": "/media/catalogMedia/BrownParfoisBag2.png",
  },
  {
    "id": `${6}-catalogDataItem`,
    "name": "Brown Hugo Boss Bag",
    "brand": "Hugo Boss",
    "price": 2999,
    "rating": 4.1,
    "color": "Brown",
    "style": "Work",
    "material": "Nylon",
    "available": "Yes",
    "model": "HugoBoss338Uo_Bag",
    "image": "/media/catalogMedia/BrownhugoBossBag.png",
  },
  {
    "id": `${7}-catalogDataItem`,
    "name": "Gray ZARA Bag",
    "brand": "Zara",
    "price": 2799,
    "rating": 4.9,
    "color": "Gray",
    "style": "Business",
    "material": "Leather",
    "available": "Yes",
    "model": "ZaraYPO90_Bag",
    "image": "/media/catalogMedia/GrayZaraBag.png",
  },
]